FROM ubuntu:20.04

LABEL SOFTWARE_NAME LINKS
LABEL MAINTAINER "Tom Harrop"
LABEL VERSION "v2.0.0"

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C

RUN     apt-get clean && \
        rm -r /var/lib/apt/lists/*

RUN     . /etc/os-release \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME} main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-backports main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> mirror.txt && \
        mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
        cat mirror.txt /etc/apt/sources.list.bak > /etc/apt/sources.list && \
        apt-get update && \
        apt-get install -y ca-certificates && \
        apt-get upgrade -y --fix-missing

RUN     apt-get update && apt-get install -y  --no-install-recommends \
            automake \
            build-essential \
            git \
            wget

RUN     git clone \
            --recursive \
            https://github.com/bcgsc/LINKS.git \
            /links

WORKDIR /links

RUN     git checkout -f v2.0.0 && \
        git submodule update --init --recursive

RUN     ./autogen.sh && ./configure && make

ENV PATH="${PATH}:/links/bin"

ENTRYPOINT ["/links/bin/LINKS"]
